services:
  tests:
    build:
      context: ./
    command: "test:ci"
    environment:
      CYPRESS_BASE_URL: $CYPRESS_BASE_URL
      BITBUCKET_BUILD_NUMBER: $BITBUCKET_BUILD_NUMBER
      CYPRESS_RECORD_KEY: $CYPRESS_RECORD_KEY
      COMMIT_INFO_BRANCH: $BITBUCKET_BRANCH
      COMMIT_INFO_MESSAGE: $COMMIT_INFO_MESSAGE
      COMMIT_INFO_EMAIL: $COMMIT_INFO_EMAIL
      COMMIT_INFO_AUTHOR: $COMMIT_INFO_AUTHOR
      COMMIT_INFO_SHA: $BITBUCKET_COMMIT
      COMMIT_INFO_REMOTE: $COMMIT_INFO_REMOTE
